name: Deploy React to AWS much fastervtt
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build docker image to test 1
        run: |
             docker build -t nkathad/docker-react -f ./client/Dockerfile.dev ./client   
             docker run  nkathad/docker-react npm test -- --coverage
  


        
