name: Deploy React to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image to test
        run: |
          docker build -t nkathad/docker-react -f ./client/Dockerfile.dev ./client  
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for prod
        run: |
          docker build -t nkathad/multiclient -f ./client/Dockerfile ./client
          docker build -t nkathad/multinginx -f ./nginx/Dockerfile ./nginx 
          docker build -t nkathad/multiserver -f ./server/Dockerfile ./server 
          docker build -t nkathad/multiworker -f ./worker/Dockerfile ./worker  
           
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to dockerhub
        run: |
          docker push nkathad/multiclient
          docker push nkathad/multinginx
          docker push nkathad/multiserver
          docker push nkathad/multiworker
         