name: Deploy React to AWS

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image for prod
        run: |
             docker build -t 8753/multiclient:latest -f ./client/Dockerfile ./client
             docker build -t 8753/multinginx -f ./nginx/Dockerfile ./nginx 
             docker build -t 8753/multiserver -f ./server/Dockerfile ./server 
             docker build -t 8753/multiworker -f ./worker/Dockerfile ./worker      
      - name: Push to dockerhub
        run: |
          docker push 8753/multiclient:latest
          docker push 8753/multinginx
          docker push 8753/multiserver
          docker push 8753/multiworker
               
      - name: Generate Deployment Package
        run: zip -r multi-docker-v47.zip Dockerrun.aws.json

      - name: Upload Deployment Package to S3
        run: |
          aws s3 cp multi-docker-v47.zip s3://elasticbeanstalk-us-east-1-216989099573/multi-docker-v47.zip --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          version_label: v47
          region: us-east-1
          existing_bucket_name: elasticbeanstalk-us-east-1-216989099573
          deployment_package: multi-docker-v47.zip
          wait_for_deployment: true
          
      
             
         
