name: Deploy React to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image to test
        run: |
          docker build -t nkathad/docker-react -f ./client/Dockerfile.dev ./client  
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image for prod
        run: |
             docker build -t nkathad/multi-client -f ./client/Dockerfile ./client
             docker build -t nkathad/multi-nginx -f ./nginx/Dockerfile ./nginx 
             docker build -t nkathad/multi-server -f ./server/Dockerfile ./server 
             docker build -t nkathad/multi-worker -f ./worker/Dockerfile ./worker      
      - name: Push to dockerhub
        run: |
          docker push nkathad/multi-client
          docker push nkathad/multi-nginx
          docker push nkathad/multi-server
          docker push nkathad/multi-worker
         