name: Deploy React to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image to test
        run: |
          docker build -t nkathad/docker-react -f ./client/Dockerfile.dev ./client  
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

     
           
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

            
    
      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
            context: ./client
            file: ./client/Dockerfile
            push: true
            tags: nkathad/multiclient:latest
     